### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by maco2035** [samuelvanderwaal/vain-purple-tiger#3]
Hey!

I am having trouble with running the program. I did a git clone of the project. And when I try to run the it, I always encounter this `error: failed to run custom build command for libsodium-sys v0.2.6` I have no clue why I am running into this. I have tried running the binary but that doesn't work either. Is there something my computer is missing?

Specs:
Ubuntu 20.04 LTS
Intel 4790
16gb DDR4

Thanks!

**Comment by samuelvanderwaal** [comment]
What version of Rust are you using and what command did you run?

**Comment by samuelvanderwaal** [comment]
A couple options to try:

Make sure you have a C compiler installed. You can get this on Ubuntu with:

`sudo apt install build-essential`

Then run `cargo build --release` or `cargo run` again. 

You can try the binary I just uploaded for v0.1.1 as I didn't have one built for that tag yet and see if that works.

**Comment by maco2035** [comment]
That was it!

I had no clue that was going to be it! I am so happy! Thank you very much!
